<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\admin\Desktop\Green.cs" Link="Green.cs" />
    <Compile Include="C:\Users\admin\Desktop\Green000001.cs" Link="Green000001.cs" />
  </ItemGroup>

</Project>
